version: 2.1
jobs:
  run_tests: 
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.16'
      - run: node --version
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
          name: Run tests
workflows:
  tests:
    jobs:
      - run_tests
