version: 2.1
orbs:
  node: circleci/node@5.1.0
jobs:
  build:
    docker:
      - image: cimg/node:16.19
    steps:
      - checkout
      - run: node --version
  run_tests:
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
          name: Run unit tests
      - run:
          command: yarn run build
          name: Build app
      - run:
          command: yarn run start-e2e-test-server
          name: Start test server
          background: true
      - run:
          command: yarn test:e2e
          name: Run e2e tests
workflows:
  build_test: 
    jobs:
      - build
      - run_tests
